name: Service2 CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./service2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set SHORT_SHA
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: veedhi1995
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t veedhi1995/service2:${SHORT_SHA} .

      - name: Push Docker Image
        run: |
          docker push veedhi1995/service2:${SHORT_SHA}
